# Copyright 2018 ConsenSys AG.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

# Project information
site_name: Hyperledger Besu
site_url: https://besu.hyperledger.org/
site_description: Hyperledger Besu Java Ethereum client documentation.
site_author: Hyperledger Besu community
copyright: Hyperledger Besu and its documentation are licensed under Apache 2.0 license /
  This <a href="https://readthedocs.org/">Readthedocs.org</a> documentation is maintained with love by <a href="https://wiki.hyperledger.org/display/besu">Hyperledger Besu community</a>.

#extra project info and template customisation
extra:
#  doc_site_edit_url: https://github.com/hyperledger/besu-docs/
  latest_version_warning:
    url_contains: /latest/
    text: 'You are reading Hyperledger Besu development version documentation and
    some displayed features may not be available in the stable release.
    You can switch to stable version using the version box at screen bottom.'
  support:
    chat: https://chat.hyperledger.org/channel/besu
    email: besu@lists.hyperledger.org
    website: https://www.hyperledger.org/projects/besu
    issues: https://github.com/hyperledger/besu/issues
    doc_issues: https://github.com/hyperledger/besu-docs/issues/new/choose
  google:
    site_verification:
      - 'sGzYdFR_AYDRtsC-SNxMRwjellnfTgs5ZA0q7GIM5j0'
    tag_manager: 'GTM-TS3WLJM'
  logo_regular: logo.svg
  logo_reversed: &logo_reversed logo-reversed.svg

# Repository
repo_name: hyperledger/besu
repo_url: https://github.com/hyperledger/besu/

theme:
    name: material
    custom_dir: custom_theme
    palette:
        primary: blue-grey
        accent: teal
    favicon: favicon.svg
    logo: *logo_reversed

extra_css:
  - assets/stylesheets/custom_theme.css
  - assets/stylesheets/zoomify.min.css
extra_javascript:
  - assets/javascripts/custom_theme.js
  - assets/javascripts/zoomify.min.js

nav:
    - How To:
        - Get Started with Besu:
            - System Requirements:
                - Private Network: HowTo/Get-Started/System-Requirements/System-Requirements-Private.md
                - Public Network: HowTo/Get-Started/System-Requirements/System-Requirements-Public.md
            - Install Besu:
                - Options: HowTo/Get-Started/Installation-Options/Options.md
                - Run Besu from Docker Image: HowTo/Get-Started/Installation-Options/Run-Docker-Image.md
                - Install Binary Distribution: HowTo/Get-Started/Installation-Options/Install-Binaries.md
                - Build from Source: HowTo/Get-Started/Installation-Options/Build-from-source.md
            - Start Besu: HowTo/Get-Started/Starting-node.md
        - Configure Besu:
          - Consensus Protocols:
            - Clique: HowTo/Configure/Consensus-Protocols/Clique.md
            - IBFT 2.0: HowTo/Configure/Consensus-Protocols/IBFT.md
            - Quorum IBFT 1.0 Network: HowTo/Configure/Consensus-Protocols/QuorumIBFT.md
            - Add Validators: HowTo/Configure/Consensus-Protocols/Add-Validators.md
          - Create Besu Genesis File: HowTo/Configure/Genesis-File.md
          - Specify Options in a Configuration File: HowTo/Configure/Using-Configuration-File.md
          - Configure a Free Gas Network: HowTo/Configure/FreeGas.md
          - Configure TLS: HowTo/Configure/Configure-TLS.md
          - High Availability:
            - Configure High Availability of APIs: HowTo/Configure/Configure-HA/High-Availability.md
            - Sample Load Balancer Configurations: HowTo/Configure/Configure-HA/Sample-Configuration.md
          - Predeploy a Contract in the Genesis File: HowTo/Configure/Contracts-in-Genesis.md
          - Configure Mining: HowTo/Configure/Configure-Mining.md
          - Pass JVM Options: HowTo/Configure/Passing-JVM-Options.md
        - Interact with Node:
            - Besu APIs:
              - Access Besu APIs: HowTo/Interact/APIs/API.md
              - Use JSON-RPC API over HTTP or WebSockets: HowTo/Interact/APIs/Using-JSON-RPC-API.md
              - Use RPC Pub/Sub API over WebSockets: HowTo/Interact/APIs/RPC-PubSub.md
              - Use GraphQL over HTTP: HowTo/Interact/APIs/GraphQL.md
              - Authenticate JSON-RPC Requests: HowTo/Interact/APIs/Authentication.md
            - Client Libraries:
              - Use the web3js-eea Client Library: HowTo/Interact/Client-Libraries/web3js-eea.md
            - Filters:
              - Access Logs Using JSON-RPC API: HowTo/Interact/Filters/Accessing-Logs-Using-JSON-RPC.md
        - Find and Connect to Peers:
          - Specify Bootnodes: HowTo/Find-and-Connect/Bootnodes.md
          - Configure Static Nodes: HowTo/Find-and-Connect/Static-Nodes.md
          - Configure Ports for Access: HowTo/Find-and-Connect/Configuring-Ports.md
          - Manage Peers: HowTo/Find-and-Connect/Managing-Peers.md
          - Specify NAT Method: HowTo/Find-and-Connect/Specifying-NAT.md
        - Monitor Nodes:
          - Use Metrics: HowTo/Monitor/Metrics.md
          - Use Quorum Hibernate: HowTo/Monitor/Quorum-Hibernate.md
          - Configure Logging: HowTo/Monitor/Logging.md
          - Use Elastic Stack: HowTo/Monitor/Elastic-Stack.md
          - Use Splunk Enterprise: HowTo/Monitor/Splunk-Enterprise.md
          - Monitor with OpenTelemetry: HowTo/Monitor/OpenTelemetry-Collector.md
        - Send Transactions:
           - Use Wallets for Key Management: HowTo/Send-Transactions/Account-Management.md
           - Create and Send Transactions: HowTo/Send-Transactions/Transactions.md
           - Create and Send Private Transactions: HowTo/Send-Transactions/Creating-Sending-Private-Transactions.md
           - Send Concurrent Private Transactions: HowTo/Send-Transactions/Concurrent-Private-Transactions.md
           - Include Revert Reason: HowTo/Send-Transactions/Revert-Reason.md
        - Limit Access to Node:
          - Use Local Permissioning: HowTo/Limit-Access/Local-Permissioning.md
          - Update Onchain Allowlists: HowTo/Limit-Access/Updating-Permission-Lists.md
          - Specify Interface Version: HowTo/Limit-Access/Specify-Perm-Version.md
        - Use Privacy Features:
          - Use EEA-compliant Privacy: HowTo/Use-Privacy/EEA-Compliant.md
          - Use Besu-extended Privacy: HowTo/Use-Privacy/Privacy.md
          - Create and Manage Privacy Groups: HowTo/Use-Privacy/Create-Manage-Privacy-Groups.md
          - Sign Privacy Marker Transactions: HowTo/Use-Privacy/Sign-Privacy-Marker-Transactions.md
          - Access Private and Privacy Marker Transactions: HowTo/Use-Privacy/Access-Private-Transactions.md
          - Run Tessera with Besu: HowTo/Use-Privacy/Run-Tessera-With-Besu.md
          - Use Flexible Privacy: HowTo/Use-Privacy/Use-FlexiblePrivacy.md
        - Deploy for Production:
          - Deploy to the Cloud: HowTo/Deploy/Cloud.md
          - Use Ansible to Deploy Besu: HowTo/Deploy/Ansible.md
          - Use Kubernetes to Deploy a Private Network: HowTo/Deploy/Kubernetes.md
          - Configure Bootnodes: HowTo/Deploy/Bootnodes.md
          - Configure Validators: HowTo/Deploy/Validators.md
          - Deploy Permissioning Management Dapp: HowTo/Deploy/Production.md
          - Use Alethio Lite Explorer: HowTo/Deploy/Lite-Block-Explorer.md
          - Use Alethio EthStats Lite Network Monitor: HowTo/Deploy/Lite-Network-Monitor.md
        - Backup and Restore: HowTo/Backup/Backup.md
        - Upgrade:
          - Upgrade Node: HowTo/Upgrade/Upgrade-Node.md
          - Upgrade Protocol: HowTo/Upgrade/Upgrade-Protocol.md
        - Develop Dapps on Besu:
          - Use Truffle: HowTo/Develop-Dapps/Truffle.md
          - Use Client Libraries: HowTo/Develop-Dapps/Client-Libraries.md
        - Troubleshoot:
          - Use EVM tool: HowTo/Troubleshoot/Use-EVM-Tool.md
          - Collect Java runtime data: HowTo/Troubleshoot/Java-Flight-Recording.md
          - Trace Transactions: HowTo/Troubleshoot/Trace-Transactions.md
          - Solve Common Problems: HowTo/Troubleshoot/Troubleshooting.md
    - Tutorials:
      - Examples:
        - Private Network Example: Tutorials/Examples/Private-Network-Example.md
        - Deploy on Microsoft Azure: Tutorials/Examples/Private-Network-Example-Azure.md
        - Private Network Example for Private Transactions: Tutorials/Examples/Privacy-Example.md
        - Configure Kubernetes mode in NAT Manager : Tutorials/Examples/Nat-Manager-Kubernetes.md
      - Create a Private Network:
        - Using Ethash (Pow): Tutorials/Private-Network/Create-Private-Network.md
        - Using Clique (PoA): Tutorials/Private-Network/Create-Private-Clique-Network.md
        - Using IBFT 2.0 (PoA): Tutorials/Private-Network/Create-IBFT-Network.md
        - Adding and Removing IBFT 2.0 Validators: Tutorials/Private-Network/Adding-removing-IBFT-validators.md
      - Permissioning:
        - Create a Permissioned Network: Tutorials/Permissioning/Create-Permissioned-Network.md
        - Get Started with Onchain Permissioning: Tutorials/Permissioning/Getting-Started-Onchain-Permissioning.md
        - Upgrade the permissioning contract: Tutorials/Permissioning/Upgrade-Permissioning-Contract.md
      - Privacy:
        - Create a Privacy-Enabled Network: Tutorials/Privacy/Configuring-Privacy.md
        - Configure a Multi-Tenant Network: Tutorials/Privacy/Configuring-Multi-Tenancy.md
        - Use web3js-eea Multinode Example: Tutorials/Privacy/web3js-eea-Multinode-example.md
      - Developer Quickstart: Tutorials/Developer-Quickstart.md
    - Concepts:
        - Architecture: Concepts/ArchitectureOverview.md
        - Consensus Protocols:
          - Overview: Concepts/Consensus-Protocols/Overview-Consensus.md
          - Comparing PoA Consensus Protocols: Concepts/Consensus-Protocols/Comparing-PoA.md
        - Plugins: Concepts/Plugins.md
        - Privacy:
          - Overview: Concepts/Privacy/Privacy-Overview.md
          - Private Transactions: Concepts/Privacy/Private-Transactions.md
          - Privacy Groups: Concepts/Privacy/Privacy-Groups.md
          - Processing Private Transactions: Concepts/Privacy/Private-Transaction-Processing.md
          - Flexible Privacy Groups: Concepts/Privacy/Flexible-PrivacyGroups.md
          - Multi-Tenancy: Concepts/Privacy/Multi-Tenancy.md
        - Permissioning:
          - Overview: Concepts/Permissioning/Permissioning-Overview.md
          - Onchain Permissioning: Concepts/Permissioning/Onchain-Permissioning.md
        - Protocol Upgrades: Concepts/Protocol-Upgrades.md
        - Pruning: Concepts/Pruning.md
        - Transactions:
          - Transaction Pool: Concepts/Transactions/Transaction-Pool.md
          - Validating Transactions: Concepts/Transactions/Transaction-Validation.md
        - Monitoring: Concepts/Monitoring.md
        - Events and Logs: Concepts/Events-and-Logs.md
        - TLS Communication: Concepts/TLS.md
        - Node Types: Concepts/Node-Types.md
        - Node Keys: Concepts/Node-Keys.md
        - Network vs Node Configuration: Concepts/Network-vs-Node.md
        - Network ID and Chain ID: Concepts/NetworkID-And-ChainID.md
        - Mining: Concepts/Mining.md
    - Reference:
        - Besu Command Line:
          - Options: Reference/CLI/CLI-Syntax.md
          - Subcommands: Reference/CLI/CLI-Subcommands.md
        - Besu API Methods: Reference/API-Methods.md
        - Besu API Objects: Reference/API-Objects.md
        - Transaction Trace Types: Reference/Trace-Types.md
        - Genesis File Items: Reference/Config-Items.md
        - web3js-eaa Reference: https://consensys.github.io/web3js-eea/latest/
        - Plugin API Interfaces: Reference/Plugin-API-Interfaces.md
        - Accounts for Testing: Reference/Accounts-for-Testing.md
        - EVM Tool: Reference/Evm-Tool.md
        - Projects Using Besu: Reference/Projects-Using-Besu.md
        - Security Disclosure Policy: Reference/Responsible-Disclosure.md
        - Blog Posts and Webinars: Reference/Resources.md

markdown_extensions:
    - toc:
        permalink: ÔÉÅ
        toc_depth: 3
    - codehilite
    - pymdownx.tabbed
    - pymdownx.superfences
    - markdown_include.include:
        base_path: docs
    - admonition
    - footnotes
    - def_list
    - abbr
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.keys
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - meta
    - smarty
    - attr_list

plugins:
    - search:
        lang: 'en'
        separator: '[\s\-\.\_]+'
    - markdownextradata
    - exclude:
        glob:
          - global/*
    - git-revision-date-localized:
        locale: en
    - minify:
        minify_html: true
        minify_js: true
        htmlmin_opts:
          remove_comments: true
    - redirects:
        redirect_maps:
          # Configure redirects using key:value pairs:
          # old_path.md: new_path.md
          # you can't use an already redirected path as an old_path.
          # new_path can be a file inside the docs/ folder or any URL (http://...)
          HowTo/Get-Started/System-Requirements-Private.md: HowTo/Get-Started/System-Requirements/System-Requirements-Private.md
          HowTo/Get-Started/System-Requirements-Public.md: HowTo/Get-Started/System-Requirements/System-Requirements-Public.md
          HowTo/Get-Started/Install-Binaries.md: HowTo/Get-Started/Installation-Options/Install-Binaries.md
          HowTo/Get-Started/Build-from-source.md: HowTo/Get-Started/Installation-Options/Build-from-source.md
          HowTo/Get-Started/Run-Docker-Image.md: HowTo/Get-Started/Installation-Options/Run-Docker-Image.md
          HowTo/Deploy/High-Availability.md: HowTo/Configure/Configure-HA/High-Availability.md
          HowTo/Deploy/Monitoring-Performance.md: HowTo/Monitor/Metrics.md
          HowTo/Upgrade/Upgrade-Network.md: HowTo/Upgrade/Upgrade-Node.md
          HowTo/Find-and-Connect/Using-UPnP.md: HowTo/Find-and-Connect/Specifying-NAT.md
          HowTo/Use-Privacy/Run-Orion-With-Besu.md: HowTo/Use-Privacy/Run-Tessera-With-Besu.md
          Concepts/Transactions/Trace-Types.md: Reference/Trace-Types.md
          HowTo/Develop-Dapps/Use-web3js.md: HowTo/Develop-Dapps/Client-Libraries.md
          Concepts/Client-Libraries.md: HowTo/Develop-Dapps/Client-Libraries.md
          Concepts/Privacy/Onchain-PrivacyGroups.md: Concepts/Privacy/Flexible-PrivacyGroups.md
          HowTo/Use-Privacy/Use-OnChainPrivacy.md: HowTo/Use-Privacy/Use-FlexiblePrivacy.md
          Tutorials/Quickstarts/Azure-Private-Network-Quickstart.md: Tutorials/Examples/Private-Network-Example-Azure.md
          HowTo/Interact/Client-Libraries/eeajs.md: HowTo/Interact/Client-Libraries/web3js-eea.md
          Privacy/Explanation/Privacy-Groups.md: Concepts/Privacy/Privacy-Groups.md
          Tutorials/Privacy/eeajs-Multinode-example.md: Tutorials/Privacy/web3js-eea-Multinode-example.md
